export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME'
export const GET_RECIPES_BY_ID = 'GET_RECIPES_BY_ID'
export const FILTER_BY_DIET = 'FILTER_BY_DIET'
export const FILTER_BY_HEALTHSCORE = 'FILTER_BY_HEALTHSCORE'
export const FILTER_BY_RECIPENAME = 'FILTER_BY_RECIPENAME'
export const GET_DIETS = 'GET_DIETS'
export const POST_RECIPE = 'POST_RECIPE'


